# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
#source 'https://github.com/CocoaPods/Specs.git'
target 'restful-api' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for restful-api

pod 'Alamofire', '~> 4.5'

end
