version: "3.9"
services:
  nginx:
    image: docker-registry.vvasylkovskyi.com:5000/neo-raspberry-nginx
    restart: always
    ports:
      - "443:443"
  server:
    image: docker-registry.vvasylkovskyi.com:5000/neo-raspberry-server
    restart: always
    ports:
      - "8084:8084"
